firstname = "Mathias"
lastname = "Dorr"

exp1 = "PO - Pricing decision and offer creation software"
exp2 = "SUPPORT BACKEND in JAVA / SQL  - EUROPEAN DEVELOPMENT FUNDS ADMINISTRATION SOFTWARE"
exp3 = "DEV FRONTEND in ANGULAR- FRENCH MINISTRY RH SOFTWARE"

pp1 = "STATIC WEBSITE - COMPUTER HARDWARE ECOMMERCE"
pp2 = "UX DESIGN - PROTEST ADMINISTRATION SOFTWARE"
pp3 = "UX DESIGN - APP for SKATERS"